<a href="https://colab.research.google.com/github/Ricardo-msj/estatistica-descritiva-python/blob/master/analise_cruzada_renda_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Imports**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dados = pd.read_csv('dados.csv')

In [ ]:
dados.head()

   UF  Sexo  Idade  Cor  Anos de Estudo  Renda    Altura
0  11     0     23    8              12    800  1.603808
1  11     1     23    2              12   1150  1.739790
2  11     1     35    8              15    880  1.760444
3  11     0     46    2               6   3500  1.783158
4  11     1     47    8               9    150  1.690631

In [ ]:
round(dados['Cor'].value_counts(normalize= True) * 100, 2)

Cor
8    46.75
2    41.40
4    10.92
0     0.46
6     0.46
Name: proportion, dtype: float64

In [ ]:
frequencia = dados['Cor'].value_counts()

In [ ]:
percentual = round(dados['Cor'].value_counts(normalize=True) * 100, 2)

In [ ]:
dist_freq_quali = pd.DataFrame({'Frequencia': frequencia, 'Percentual(%)': percentual})

In [ ]:
dist_freq_quali

     Frequencia  Percentual(%)
Cor
8         35925          46.75
2         31815          41.40
4          8391          10.92
0           357           0.46
6           352           0.46

In [ ]:
dist_freq_quali.rename(index= {0:'indigena', 2:'Branca', 4:'Preta', 6:'Amarela', 8:'Parda', 9: 'Sem Declaracao'}, inplace= True)
dist_freq_quali.rename_axis('Cor da Pele', axis = 'columns', inplace=True)
dist_freq_quali.rename_axis(None, axis = 'index', inplace=True)

In [ ]:
dist_freq_quali

Cor da Pele  Frequencia  Percentual(%)
Parda             35925          46.75
Branca            31815          41.40
Preta              8391          10.92
indigena            357           0.46
Amarela             352           0.46

In [ ]:
cor = {0:'indigena',
       2:'Branca',
       4:'Preta',
       6:'Amarela',
       8:'Parda',
       9: 'Sem Declaracao'}

sexo = {0:'Masculino',
        1:'Feminino'}

In [ ]:
frquencia2 = pd.crosstab(dados.Sexo,
                        dados.Cor,
                        aggfunc= 'mean',
                        values= dados.Renda,
                        )


frquencia2.rename(index=sexo, columns=cor, inplace = True)
frquencia2

Cor           indigena       Branca        Preta      Amarela        Parda
Sexo
Masculino  1081.710938  2925.744435  1603.861687  4758.251064  1659.577425
Feminino   2464.386139  2109.866750  1134.596400  3027.341880  1176.758516