<a href="https://colab.research.google.com/github/Ricardo-msj/estatistica-descritiva-python/blob/master/classificacao_renda_analise_quantitativa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Imports**

In [ ]:
import pandas as pd
import numpy as np

#**analise Quantitativa**


---


    A: acima de R$15.760,00;
    B: de R$7.880,00 até R$15.760,00;
    C: de R$3.152,00 até R$ 7.880,00;
    D: de R$1.576,00 até R$3.152,00;
    E: de zero até R$1.576,00.

In [ ]:
dados.Renda.min()

0

In [ ]:
dados.Renda.max()

200000

In [ ]:
classes = [0, 1576,3152, 7880, 15760, 200000]
labels = ['E', 'D', 'C', 'B', 'A']

In [ ]:
frequencia_renda = pd.cut(
    x = dados.Renda,
    bins = classes,
    labels = labels,
    include_lowest = True
    ).value_counts()

frequencia_renda.sort_index(ascending=False)

Renda
A      608
B     2178
C     7599
D    16700
E    49755
Name: count, dtype: int64

In [ ]:
percentual_renda = pd.cut(
    x = dados.Renda,
    bins = classes,
    labels = labels,
    include_lowest = True
    ).value_counts(normalize=True) * 100

percentual_renda.sort_index(ascending=False)

Renda
A     0.791255
B     2.834461
C     9.889381
D    21.733472
E    64.751432
Name: proportion, dtype: float64

In [ ]:
distri_freq_quantitativa = pd.DataFrame({'Frequencia': frequencia_renda, 'Percentual': percentual_renda}).sort_index(ascending=False)
distri_freq_quantitativa.rename_axis(None, axis='index', inplace = True)
distri_freq_quantitativa.rename_axis('Classes', axis='columns', inplace=True)
distri_freq_quantitativa

Classes  Frequencia  Percentual
A               608    0.791255
B              2178    2.834461
C              7599    9.889381
D             16700   21.733472
E             49755   64.751432